preload = ~/.config/backgrounds/mountain.jpeg
preload = ~/.config/backgrounds/shaded.png
preload = ~/.config/backgrounds/lofiwallpaper.png
preload = ~/.config/backgrounds/nice-blue-background.png
preload = ~/.config/backgrounds/shaded.png

wallpaper {
  monitor = eDP-1
  path = ~/.config/backgrounds/shaded.png
  fit_mode = cover
}

splash = false
ipc = off
